### ISSUE TITLE
Issue-3-user-can-start-their-car

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Listen for keydown for 'space'
- [x] Create function that 'moves' image
- [x] Set interval for 16ms
